console.log (`OUTRE-REVE || SCRIPT - initiatlizing CONFIG-CEF (const)`);
const FLEUVE_COORD = 'Fleuve'
// /** lien vers l'illustration de la Carte des Eaux du Fleuve (CEF) */
// const IMAGE_CEF = "modules/a-perte-de-reve/assets/tmr-CEF.webp" //Tahmos

/******************************************
 **      Climat des Eaux du Fleuve       **
*******************************************/
/** Niveaux du climat CEF et les risques de rencontre (valeur du Dé Draconique) */
const RDD_CEF = { 
    Climat : [  
        {value: "0", jetRencontre: 7, rencontreMin : 0, visu: "≈ ≈ ≈ ≈ ≈ ≈ ≈", label: "Terres Médianes du Rêve"},
        {value: "1", jetRencontre: 8, rencontreMin : 1, visu: "① ≈ ≈ ≈ ≈ ≈ ≈", label: "Beau Fixe"},
        {value: "2", jetRencontre: 8, rencontreMin : 2, visu: "≈ ② ≈ ≈ ≈ ≈ ≈", label: "Fleuve d'Huille"},
        {value: "3", jetRencontre: 8, rencontreMin : 3, visu: "≈ ≈ ③ ≈ ≈ ≈ ≈", label: "Brûmes"},
        {value: "4", jetRencontre: 8, rencontreMin : 4, visu: "≈ ≈ ≈ ④ ≈ ≈ ≈", label: "Vents Traversiers"},
        {value: "5", jetRencontre: 7, rencontreMin : 5, visu: "≈ ≈ ≈ ≈ ⑤ ≈ ≈", label: "Houle Croisée"},
        {value: "6", jetRencontre: 6, rencontreMin : 6, visu: "≈ ≈ ≈ ≈ ≈ ⑥ ≈", label: "Tempête"},
        {value: "7", jetRencontre: 5, rencontreMin : 7, visu: "≈ ≈ ≈ ≈ ≈ ≈ ⑦", label: "Crue"},
    ],
    Image : "modules/a-perte-de-reve/assets/tmr-CEF.webp"
}

/*****************************************
 **         Types de Terrains           **
******************************************/
// Types de terrain en TMR
const TMRType = {
    cite:       { type: 'cite',         name: "cité",       genre: "f" },
    sanctuaire: { type: 'sanctuaire',   name: "sanctuaire", genre: 'm' },
    plaines:    { type: 'plaines',      name: "plaines",    genre: "fp" },
    pont:       { type: 'pont',         name: "pont",       genre: "m" },
    collines:   { type: 'collines',     name: "collines",   genre: "p" },
    foret:      { type: 'foret',        name: "forêt",      genre: "f" },
    monts:      { type: 'monts',        name: "monts",      genre: "p" },
    desert:     { type: 'desert',       name: "désert",     genre: "m" },
    fleuve:     { type: 'fleuve',       name: "fleuve",     genre: "m" },
    lac:        { type: 'lac',          name: "lac",        genre: "m" },
    marais:     { type: 'marais',       name: "marais",     genre: "m" },
    gouffre:    { type: 'gouffre',      name: "gouffre",    genre: "m" },
    necropole:  { type: 'necropole',    name: "nécropole",  genre: "f" },
    desolation: { type: 'desolation',   name: "désolation", genre: "f" }
}
/** Type de terrain en CEF (gardant le 'type' identique aux TMR pour garder le mapping des sorts) */
const CEFType = {
    cite:       { type: 'cite',         name: "sémaphore",  genre: "m" },
    sanctuaire: { type: 'sanctuaire',   name: "chenal",     genre: 'm' },
    plaines:    { type: 'plaines',      name: "banc",       genre: "m" },
    pont:       { type: 'pont',         name: "île",        genre: "f" },
    collines:   { type: 'collines',     name: "source",     genre: "f" },
    foret:      { type: 'foret',        name: "rapide",     genre: "m" },
    monts:      { type: 'monts',        name: "chute",      genre: "f" },
    desert:     { type: 'desert',       name: "méandre",    genre: "m" },
    fleuve:     { type: 'fleuve',       name: "fleuve",     genre: "m" },
    lac:        { type: 'lac',          name: "lac",        genre: "m" },
    marais:     { type: 'marais',       name: "marais",     genre: "m" },
    gouffre:    { type: 'gouffre',      name: "abîme",      genre: "m" },
    necropole:  { type: 'necropole',    name: "maelstrom",  genre: "m" },
    desolation: { type: 'desolation',   name: "écueils",    genre: "p" }
}

/*************************************************
 **      Mapping des Cases (types & Label)      **
**************************************************/
// Mapping des cases TMR
const TMRMap = {
    Fleuve: { type: TMRType.fleuve.type, label: "Fleuve de l'Oubli", generique: 'fleuve' },
    A1: { type: TMRType.cite.type, label: "Cité Vide" },
    B1: { type: TMRType.plaines.type, label: "Plaines d’Assorh" },
    C1: { type: TMRType.necropole.type, label: "Nécropole de Kroak" },
    D1: { type: TMRType.fleuve.type, label: "Fleuve de l'Oubli" },
    E1: { type: TMRType.monts.type, label: "Monts de Kanaï" },
    F1: { type: TMRType.cite.type, label: "Cité Glauque" },
    G1: { type: TMRType.desolation.type, label: "Désolation de Jamais" },
    H1: { type: TMRType.lac.type, label: "Lac d’Anticalme" },
    I1: { type: TMRType.plaines.type, label: "Plaines Grises" },
    J1: { type: TMRType.monts.type, label: "Monts Fainéants" },
    K1: { type: TMRType.cite.type, label: "Cité d’Onkause" },
    L1: { type: TMRType.fleuve.type, label: "Fleuve de l'Oubli" },
    M1: { type: TMRType.cite.type, label: "Cité Jalouse" },
    A2: { type: TMRType.desert.type, label: "Désert de Mieux" },
    B2: { type: TMRType.collines.type, label: "Collines de Dawell" },
    C2: { type: TMRType.marais.type, label: "Marais Glignants" },
    D2: { type: TMRType.cite.type, label: "Cité de Frost" },
    E2: { type: TMRType.plaines.type, label: "Plaines de Fiask" },
    F2: { type: TMRType.lac.type, label: "Lac de Misère" },
    G2: { type: TMRType.marais.type, label: "Marais Nuisants" },
    H2: { type: TMRType.collines.type, label: "Collines de Parta" },
    I2: { type: TMRType.foret.type, label: "Forêt Fade" },
    J2: { type: TMRType.desert.type, label: "Désert de Poly" },
    K2: { type: TMRType.foret.type, label: "Forêt Tamée" },
    L2: { type: TMRType.fleuve.type, label: "Fleuve de l'Oubli" },
    M2: { type: TMRType.necropole.type, label: "Nécropole de Logos" },
    A3: { type: TMRType.desolation.type, label: "Désolation de Demain" },
    B3: { type: TMRType.plaines.type, label: "Plaines de Rubéga" },
    C3: { type: TMRType.fleuve.type, label: "Fleuve de l'Oubli" },
    D3: { type: TMRType.gouffre.type, label: "Gouffre d’Oki" },
    E3: { type: TMRType.foret.type, label: "Forêt d’Estoubh" },
    F3: { type: TMRType.fleuve.type, label: "Fleuve de l'Oubli" },
    G3: { type: TMRType.gouffre.type, label: "Gouffre de Sun" },
    H3: { type: TMRType.foret.type, label: "Forêt de Ganna" },
    I3: { type: TMRType.monts.type, label: "Monts Grinçants" },
    J3: { type: TMRType.cite.type, label: "Cité Venin" },
    K3: { type: TMRType.plaines.type, label: "Plaines de Dois" },
    L3: { type: TMRType.lac.type, label: "Lac Laineux" },
    M3: { type: TMRType.monts.type, label: "Monts de Vdah" },
    A4: { type: TMRType.foret.type, label: "Forêt de Falconax" },
    B4: { type: TMRType.monts.type, label: "Monts Crâneurs" },
    C4: { type: TMRType.pont.type, label: "Pont de Giolii" },
    D4: { type: TMRType.lac.type, label: "Lac de Foam" },
    E4: { type: TMRType.plaines.type, label: "Plaines d’Orti" },
    F4: { type: TMRType.fleuve.type, label: "Fleuve de l'Oubli" },
    G4: { type: TMRType.sanctuaire.type, label: "Sanctuaire Blanc" },
    H4: { type: TMRType.plaines.type, label: "Plaines de Psark" },
    I4: { type: TMRType.plaines.type, label: "Plaines de Xiax" },
    J4: { type: TMRType.collines.type, label: "Collines d’Encre" },
    K4: { type: TMRType.pont.type, label: "Pont de Fah" },
    L4: { type: TMRType.sanctuaire.type, label: "Sanctuaire Mauve" },
    M4: { type: TMRType.gouffre.type, label: "Gouffre Grisant" },
    A5: { type: TMRType.plaines.type, label: "Plaines de Trilkh" },
    B5: { type: TMRType.collines.type, label: "Collines de Tanegy" },
    C5: { type: TMRType.marais.type, label: "Marais Flouants" },
    D5: { type: TMRType.fleuve.type, label: "Fleuve de l'Oubli" },
    E5: { type: TMRType.monts.type, label: "Monts Brûlants" },
    F5: { type: TMRType.cite.type, label: "Cité de Panople" },
    G5: { type: TMRType.pont.type, label: "Pont d’Ik" },
    H5: { type: TMRType.desert.type, label: "Désert de Krane" },
    I5: { type: TMRType.desolation.type, label: "Désolation de Toujours" },
    J5: { type: TMRType.marais.type, label: "Marais de Jab" },
    K5: { type: TMRType.fleuve.type, label: "Fleuve de l'Oubli" },
    L5: { type: TMRType.collines.type, label: "Collines Suaves" },
    M5: { type: TMRType.cite.type, label: "Cité Rimarde" },
    A6: { type: TMRType.necropole.type, label: "Nécropole de Zniak" },
    B6: { type: TMRType.foret.type, label: "Forêt de Bust" },
    C6: { type: TMRType.cite.type, label: "Cité Pavois" },
    D6: { type: TMRType.fleuve.type, label: "Fleuve de l'Oubli" },
    E6: { type: TMRType.sanctuaire.type, label: "Sanctuaire de Plaine" },
    F6: { type: TMRType.fleuve.type, label: "Fleuve de l'Oubli" },
    G6: { type: TMRType.marais.type, label: "Marais Glutants" },
    H6: { type: TMRType.monts.type, label: "Monts Gurdes" },
    I6: { type: TMRType.necropole.type, label: "Nécropole de Xotar" },
    J6: { type: TMRType.lac.type, label: "Lac d’Iaupe" },
    K6: { type: TMRType.desolation.type, label: "Désolation de Poor" },
    L6: { type: TMRType.foret.type, label: "Forêt Gueuse" },
    M6: { type: TMRType.desolation.type, label: "Désolation de Presque" },
    A7: { type: TMRType.plaines.type, label: "Plaines de l’Arc" },
    B7: { type: TMRType.marais.type, label: "Marais Bluants" },
    C7: { type: TMRType.fleuve.type, label: "Fleuve de l'Oubli" },
    D7: { type: TMRType.plaines.type, label: "Plaines d’Affa" },
    E7: { type: TMRType.foret.type, label: "Forêt de Glusks" },
    F7: { type: TMRType.fleuve.type, label: "Fleuve de l'Oubli" },
    G7: { type: TMRType.cite.type, label: "Cité de Terwa" },
    H7: { type: TMRType.gouffre.type, label: "Gouffre de Kapfa" },
    I7: { type: TMRType.plaines.type, label: "Plaines de Troo" },
    J7: { type: TMRType.fleuve.type, label: "Fleuve de l'Oubli" },
    K7: { type: TMRType.cite.type, label: "Cité de Kolix" },
    L7: { type: TMRType.gouffre.type, label: "Gouffre d’Episophe" },
    M7: { type: TMRType.desert.type, label: "Désert de Lave" },
    A8: { type: TMRType.gouffre.type, label: "Gouffre de Shok" },
    B8: { type: TMRType.fleuve.type, label: "Fleuve de l'Oubli" },
    C8: { type: TMRType.foret.type, label: "Forêt Turmide" },
    D8: { type: TMRType.cite.type, label: "Cité d’Olak" },
    E8: { type: TMRType.plaines.type, label: "Plaines d’Iolise" },
    F8: { type: TMRType.lac.type, label: "Lac des Chats" },
    G8: { type: TMRType.plaines.type, label: "Plaines Sans Joie" },
    H8: { type: TMRType.foret.type, label: "Forêt d’Ourf" },
    I8: { type: TMRType.fleuve.type, label: "Fleuve de l'Oubli" },
    J8: { type: TMRType.monts.type, label: "Monts Barask" },
    K8: { type: TMRType.desert.type, label: "Désert de Fumée" },
    L8: { type: TMRType.monts.type, label: "Monts Tavelés" },
    M8: { type: TMRType.plaines.type, label: "Plaines Lavées" },
    A9: { type: TMRType.collines.type, label: "Collines de Korrex" },
    B9: { type: TMRType.lac.type, label: "Lac de Lucre" },
    C9: { type: TMRType.monts.type, label: "Monts Tuméfiés" },
    D9: { type: TMRType.pont.type, label: "Pont d’Orx" },
    E9: { type: TMRType.fleuve.type, label: "Fleuve de l'Oubli" },
    F9: { type: TMRType.plaines.type, label: "Plaines de Foe" },
    G9: { type: TMRType.desolation.type, label: "Désolation de Sel" },
    H9: { type: TMRType.collines.type, label: "Collines de Noirseul" },
    I9: { type: TMRType.fleuve.type, label: "Fleuve de l'Oubli" },
    J9: { type: TMRType.marais.type, label: "Marais Gronchants" },
    K9: { type: TMRType.sanctuaire.type, label: "Sanctuaire Noir" },
    L9: { type: TMRType.collines.type, label: "Collines Cornues" },
    M9: { type: TMRType.necropole.type, label: "Nécropole de Zonar" },
    A10: { type: TMRType.sanctuaire.type, label: "Sanctuaire d’Olis" },
    B10: { type: TMRType.monts.type, label: "Monts Salés" },
    C10: { type: TMRType.marais.type, label: "Marais de Dom" },
    D10: { type: TMRType.fleuve.type, label: "Fleuve de l'Oubli" },
    E10: { type: TMRType.gouffre.type, label: "Gouffre de Junk" },
    F10: { type: TMRType.marais.type, label: "Marais Zultants" },
    G10: { type: TMRType.cite.type, label: "Cité de Sergal" },
    H10: { type: TMRType.plaines.type, label: "Plaines Noires" },
    I10: { type: TMRType.lac.type, label: "Lac Wanito" },
    J10: { type: TMRType.fleuve.type, label: "Fleuve de l'Oubli" },
    K10: { type: TMRType.plaines.type, label: "Plaines Jaunes" },
    L10: { type: TMRType.desert.type, label: "Désert de Nicrop" },
    M10: { type: TMRType.foret.type, label: "Forêt de Jajou" },
    A11: { type: TMRType.desolation.type, label: "Désolation d’Hier" },
    B11: { type: TMRType.cite.type, label: "Cité de Brilz" },
    C11: { type: TMRType.pont.type, label: "Pont de Roï" },
    D11: { type: TMRType.desolation.type, label: "Désolation de Partout" },
    E11: { type: TMRType.lac.type, label: "Lac de Glinster" },
    F11: { type: TMRType.cite.type, label: "Cité de Noape" },
    G11: { type: TMRType.fleuve.type, label: "Fleuve de l'Oubli" },
    H11: { type: TMRType.fleuve.type, label: "Fleuve de l'Oubli" },
    I11: { type: TMRType.pont.type, label: "Pont de Yalm" },
    J11: { type: TMRType.plaines.type, label: "Plaines de Miltiar" },
    K11: { type: TMRType.cite.type, label: "Cité Tonnerre" },
    L11: { type: TMRType.collines.type, label: "Collines de Kol" },
    M11: { type: TMRType.cite.type, label: "Cité Crapaud" },
    A12: { type: TMRType.plaines.type, label: "Plaines Sages" },
    B12: { type: TMRType.fleuve.type, label: "Fleuve de l'Oubli" },
    C12: { type: TMRType.lac.type, label: "Lac de Fricassa" },
    D12: { type: TMRType.collines.type, label: "Collines d’Huaï" },
    E12: { type: TMRType.monts.type, label: "Monts Ajourés" },
    F12: { type: TMRType.necropole.type, label: "Nécropole de Throat" },
    G12: { type: TMRType.plaines.type, label: "Plaines de Lufmil" },
    H12: { type: TMRType.collines.type, label: "Collines de Tooth" },
    I12: { type: TMRType.gouffre.type, label: "Gouffre Abimeux" },
    J12: { type: TMRType.cite.type, label: "Cité Folle" },
    K12: { type: TMRType.desolation.type, label: "Désolation d’Amour" },
    L12: { type: TMRType.plaines.type, label: "Plaines Venteuses" },
    M12: { type: TMRType.collines.type, label: "Collines Révulsantes" },
    A13: { type: TMRType.fleuve.type, label: "Fleuve de l'Oubli" },
    B13: { type: TMRType.gouffre.type, label: "Gouffre des Litiges" },
    C13: { type: TMRType.desert.type, label: "Désert de Neige" },
    D13: { type: TMRType.cite.type, label: "Cité Sordide" },
    E13: { type: TMRType.plaines.type, label: "Plaines de Xnez" },
    F13: { type: TMRType.foret.type, label: "Forêt des Cris" },
    G13: { type: TMRType.plaines.type, label: "Plaines Calcaires" },
    H13: { type: TMRType.desolation.type, label: "Désolation de Rien" },
    I13: { type: TMRType.monts.type, label: "Monts Bigleux" },
    J13: { type: TMRType.gouffre.type, label: "Gouffre de Gromph" },
    K13: { type: TMRType.foret.type, label: "Forêt de Kluth" },
    L13: { type: TMRType.monts.type, label: "Monts Dormants" },
    M13: { type: TMRType.plaines.type, label: "Plaines d’Anjou" },
    A14: { type: TMRType.collines.type, label: "Collines de Stolis" },
    B14: { type: TMRType.necropole.type, label: "Nécropole de Gorlo" },
    C14: { type: TMRType.foret.type, label: "Forêt de Bissam" },
    D14: { type: TMRType.sanctuaire.type, label: "Sanctuaire Plat" },
    E14: { type: TMRType.monts.type, label: "Monts de Quath" },
    F14: { type: TMRType.plaines.type, label: "Plaines Brisées" },
    G14: { type: TMRType.desert.type, label: "Désert de Sek" },
    H14: { type: TMRType.plaines.type, label: "Plaines Blanches" },
    I14: { type: TMRType.cite.type, label: "Cité Destituée" },
    J14: { type: TMRType.desert.type, label: "Désert de Sank" },
    K14: { type: TMRType.necropole.type, label: "Nécropole d’Antinéar" },
    L14: { type: TMRType.plaines.type, label: "Plaines de Jislith" },
    M14: { type: TMRType.desolation.type, label: "Désolation d’Après" },
    A15: { type: TMRType.cite.type, label: "Cité de Mielh" },
    C15: { type: TMRType.plaines.type, label: "Plaines de Toué" },
    E15: { type: TMRType.foret.type, label: "Forêt des Furies" },
    G15: { type: TMRType.plaines.type, label: "Plaines des Soupirs" },
    I15: { type: TMRType.monts.type, label: "Monts des Dragées" },
    K15: { type: TMRType.collines.type, label: "Collines Pourpres" },
    M15: { type: TMRType.cite.type, label: "Cité de Klana" }
}
// Mapping des case CEF... avec encore beaucoup de lieux dont le nom reste inconnu
const CEFMap = {       // const CEFMapping = {
    // var TMRMapping = CEFMap; // Tahmos switching TMRMap<-->CEFMap in "tmr-utility"
    Fleuve: { type: CEFType.fleuve.type, label: "Fleuve de l'Oubli", generique: 'fleuve' },
    A1: { type: CEFType.cite.type, label: "Sémaphore ...\n(Cité Vide)" },
    B1: { type: CEFType.plaines.type, label: "Banc ...\n(Plaines d’Assorh)" },
    C1: { type: CEFType.necropole.type, label: "Maelstrom de 'K'\n(Nécropole de Kroak)" },
    D1: { type: CEFType.fleuve.type, label: "Fleuve de l'Oubli" },
    E1: { type: CEFType.monts.type, label: "Chute ...\n(Monts de Kanaï)" },
    F1: { type: CEFType.cite.type, label: "Sémaphore ...\n(Cité Glauque)" },
    G1: { type: CEFType.desolation.type, label: "Ecueils ...\n(Désolation de Jamais)" },
    H1: { type: CEFType.lac.type, label: "Lac (d’Anticalme)" },
    I1: { type: CEFType.plaines.type, label: "Banc ...\n(Plaines Grises)" },
    J1: { type: CEFType.monts.type, label: "Chute ...\n(Monts Fainéants)" },
    K1: { type: CEFType.cite.type, label: "Sémaphore ...\n(Cité d’Onkause)" },
    L1: { type: CEFType.fleuve.type, label: "Fleuve de l'Oubli" },
    M1: { type: CEFType.cite.type, label: "Sémaphore ...\n(Cité Jalouse)" },
    A2: { type: CEFType.desert.type, label: "Méandre ...\n(Désert de Mieux)" },
    B2: { type: CEFType.collines.type, label: "Source ...\n(Collines de Dawell)" },
    C2: { type: CEFType.marais.type, label: "Marais (Glignants)" },
    D2: { type: CEFType.cite.type, label: "Sémaphore ...\n(Cité de Frost)" },
    E2: { type: CEFType.plaines.type, label: "Banc ...\n(Plaines de Fiask)" },
    F2: { type: CEFType.lac.type, label: "Lac (de Misère)" },
    G2: { type: CEFType.marais.type, label: "Marais (Nuisants)" },
    H2: { type: CEFType.collines.type, label: "Source ...\n(Collines de Parta)" },
    I2: { type: CEFType.foret.type, label: "Rapide ...\n(Forêt Fade)" },
    J2: { type: CEFType.desert.type, label: "Méandre ...\n(Désert de Poly)" },
    K2: { type: CEFType.foret.type, label: "Rapide ...\n(Forêt Tamée)" },
    L2: { type: CEFType.fleuve.type, label: "Fleuve de l'Oubli" },
    M2: { type: CEFType.necropole.type, label: "Maelstrom ...\n(Nécropole de Logos)" },
    A3: { type: CEFType.desolation.type, label: "Ecueils ...\n(Désolation de Demain)" },
    B3: { type: CEFType.plaines.type, label: "Banc ...\n(Plaines de Rubéga)" },
    C3: { type: CEFType.fleuve.type, label: "Fleuve de l'Oubli" },
    D3: { type: CEFType.gouffre.type, label: "Abîme d'Iko\n(Gouffre d’Oki)" },
    E3: { type: CEFType.foret.type, label: "Rapide ...\n(Forêt d’Estoubh)" },
    F3: { type: CEFType.fleuve.type, label: "Fleuve de l'Oubli" },
    G3: { type: CEFType.gouffre.type, label: "Abîme ...\n(Gouffre de Sun)" },
    H3: { type: CEFType.foret.type, label: "Rapide ...\n(Forêt de Ganna)" },
    I3: { type: CEFType.monts.type, label: "Chute ...\n(Monts Grinçants)" },
    J3: { type: CEFType.cite.type, label: "Sémaphore ...\n(Cité Venin)" },
    K3: { type: CEFType.plaines.type, label: "Banc ...\n(Plaines de Dois)" },
    L3: { type: CEFType.lac.type, label: "Lac (Laineux)" },
    M3: { type: CEFType.monts.type, label: "Chute ...\n(Monts de Vdah)" },
    A4: { type: CEFType.foret.type, label: "Rapide ...\n(Forêt de Falconax)" },
    B4: { type: CEFType.monts.type, label: "Chute ...\n(Monts Crâneurs)" },
    C4: { type: CEFType.pont.type, label: "Île ...\n(Pont de Giolii)" },
    D4: { type: CEFType.lac.type, label: "Lac (de Foam)" },
    E4: { type: CEFType.plaines.type, label: "Banc ...\n(Plaines d’Orti)" },
    F4: { type: CEFType.fleuve.type, label: "Fleuve de l'Oubli" },
    G4: { type: CEFType.sanctuaire.type, label: "Chenal ...\n(Sanctuaire Blanc)" },
    H4: { type: CEFType.plaines.type, label: "Banc ...\n(Plaines de Psark)" },
    I4: { type: CEFType.plaines.type, label: "Banc ...\n(Plaines de Xiax)" },
    J4: { type: CEFType.collines.type, label: "Source ...\n(Collines d’Encre)" },
    K4: { type: CEFType.pont.type, label: "Île ...\n(Pont de Fah)" },
    L4: { type: CEFType.sanctuaire.type, label: "Chenal ...\n(Sanctuaire Mauve)" },
    M4: { type: CEFType.gouffre.type, label: "Abîme ...\n(Gouffre Grisant)" },
    A5: { type: CEFType.plaines.type, label: "Banc ...\n(Plaines de Trilkh)" },
    B5: { type: CEFType.collines.type, label: "Source ...\n(Collines de Tanegy)" },
    C5: { type: CEFType.marais.type, label: "Marais (Flouants)" },
    D5: { type: CEFType.fleuve.type, label: "Fleuve de l'Oubli" },
    E5: { type: CEFType.monts.type, label: "Chute ...\n(Monts Brûlants)" },
    F5: { type: CEFType.cite.type, label: "Sémaphore ...\n(Cité de Panople)" },
    G5: { type: CEFType.pont.type, label: "Île ...\n(Pont d’Ik)" },
    H5: { type: CEFType.desert.type, label: "Méandre ...\n(Désert de Krane)" },
    I5: { type: CEFType.desolation.type, label: "Ecueils ...\n(Désolation de Toujours)" },
    J5: { type: CEFType.marais.type, label: "Marais (de Jab)" },
    K5: { type: CEFType.fleuve.type, label: "Fleuve de l'Oubli" },
    L5: { type: CEFType.collines.type, label: "Source ...\n(Collines Suaves)" },
    M5: { type: CEFType.cite.type, label: "Sémaphore ...\n(Cité Rimarde)" },
    A6: { type: CEFType.necropole.type, label: "Maelstrom ...\n(Nécropole de Zniak)" },
    B6: { type: CEFType.foret.type, label: "Rapide ...\n(Forêt de Bust)" },
    C6: { type: CEFType.cite.type, label: "Sémaphore ...\n(Cité Pavois)" },
    D6: { type: CEFType.fleuve.type, label: "Fleuve de l'Oubli" },
    E6: { type: CEFType.sanctuaire.type, label: "Chenal ...\n(Sanctuaire de Plaine)" },
    F6: { type: CEFType.fleuve.type, label: "Fleuve de l'Oubli" },
    G6: { type: CEFType.marais.type, label: "Marais (Glutants)" },
    H6: { type: CEFType.monts.type, label: "Chute ...\n(Monts Gurdes)" },
    I6: { type: CEFType.necropole.type, label: "Maelstrom ...\n(Nécropole de Xotar)" },
    J6: { type: CEFType.lac.type, label: "Lac (d’Iaupe)" },
    K6: { type: CEFType.desolation.type, label: "Ecueils ...\n(Désolation de Poor)" },
    L6: { type: CEFType.foret.type, label: "Rapide ...\n(Forêt Gueuse)" },
    M6: { type: CEFType.desolation.type, label: "Ecueils ...\n(Désolation de Presque)" },
    A7: { type: CEFType.plaines.type, label: "Banc ...\n(Plaines de l’Arc)" },
    B7: { type: CEFType.marais.type, label: "Marais (Bluants)" },
    C7: { type: CEFType.fleuve.type, label: "Fleuve de l'Oubli" },
    D7: { type: CEFType.plaines.type, label: "Banc ...\n(Plaines d’Affa)" },
    E7: { type: CEFType.foret.type, label: "Rapide ...\n(Forêt de Glusks)" },
    F7: { type: CEFType.fleuve.type, label: "Fleuve de l'Oubli" },
    G7: { type: CEFType.cite.type, label: "Sémaphore ...\n(Cité de Terwa)" },
    H7: { type: CEFType.gouffre.type, label: "Abîme ...\n(Gouffre de Kapfa)" },
    I7: { type: CEFType.plaines.type, label: "Banc ...\n(Plaines de Troo)" },
    J7: { type: CEFType.fleuve.type, label: "Fleuve de l'Oubli" },
    K7: { type: CEFType.cite.type, label: "Sémaphore ...\n(Cité de Kolix)" },
    L7: { type: CEFType.gouffre.type, label: "Abîme ...\n(Gouffre d’Episophe)" },
    M7: { type: CEFType.desert.type, label: "Méandre ...\n(Désert de Lave)" },
    A8: { type: CEFType.gouffre.type, label: "Abîme ...\n(Gouffre de Shok)" },
    B8: { type: CEFType.fleuve.type, label: "Fleuve de l'Oubli" },
    C8: { type: CEFType.foret.type, label: "Rapide ...\n(Forêt Turmide)" },
    D8: { type: CEFType.cite.type, label: "Sémaphore ...\n(Cité d’Olak)" },
    E8: { type: CEFType.plaines.type, label: "Banc ...\n(Plaines d’Iolise)" },
    F8: { type: CEFType.lac.type, label: "Lac (des Chats)" },
    G8: { type: CEFType.plaines.type, label: "PIC de la Chimère\n(Plaines Sans Joie)" },
    H8: { type: CEFType.foret.type, label: "Rapide ...\n(Forêt d’Ourf)" },
    I8: { type: CEFType.fleuve.type, label: "Fleuve de l'Oubli" },
    J8: { type: CEFType.monts.type, label: "Chute ...\n(Monts Barask)" },
    K8: { type: CEFType.desert.type, label: "Méandre ...\n(Désert de Fumée)" },
    L8: { type: CEFType.monts.type, label: "Chute ...\n(Monts Tavelés)" },
    M8: { type: CEFType.plaines.type, label: "Banc ...\n(Plaines Lavées)" },
    A9: { type: CEFType.collines.type, label: "Source ...\n(Collines de Korrex)" },
    B9: { type: CEFType.lac.type, label: "Lac (de Lucre)" },
    C9: { type: CEFType.monts.type, label: "Chute ...\n(Monts Tuméfiés)" },
    D9: { type: CEFType.pont.type, label: "Île ...\n(Pont d’Orx)" },
    E9: { type: CEFType.fleuve.type, label: "Fleuve de l'Oubli" },
    F9: { type: CEFType.plaines.type, label: "Banc ...\n(Plaines de Foe)" },
    G9: { type: CEFType.desolation.type, label: "Ecueils de Sora\n(Désolation de Sel)" },
    H9: { type: CEFType.collines.type, label: "Source ...\n(Collines de Noirseul)" },
    I9: { type: CEFType.fleuve.type, label: "Fleuve de l'Oubli" },
    J9: { type: CEFType.marais.type, label: "Marais (Gronchants)" },
    K9: { type: CEFType.sanctuaire.type, label: "Chenal ...\n(Sanctuaire Noir)" },
    L9: { type: CEFType.collines.type, label: "Source ...\n(Collines Cornues)" },
    M9: { type: CEFType.necropole.type, label: "Maelstrom ...\n(Nécropole de Zonar)" },
    A10: { type: CEFType.sanctuaire.type, label: "Chenal ...\n(Sanctuaire d’Olis)" },
    B10: { type: CEFType.monts.type, label: "Chute ...\n(Monts Salés)" },
    C10: { type: CEFType.marais.type, label: "Marais (de Dom)" },
    D10: { type: CEFType.fleuve.type, label: "Fleuve de l'Oubli" },
    E10: { type: CEFType.gouffre.type, label: "Abîme ...\n(Gouffre de Junk)" },
    F10: { type: CEFType.marais.type, label: "Marais (Zultants)" },
    G10: { type: CEFType.cite.type, label: "Sémaphore ...\n(Cité de Sergal)" },
    H10: { type: CEFType.plaines.type, label: "Banc ...\n(Plaines Noires)" },
    I10: { type: CEFType.lac.type, label: "Lac (Wanito)" },
    J10: { type: CEFType.fleuve.type, label: "Fleuve de l'Oubli" },
    K10: { type: CEFType.plaines.type, label: "Banc ...\n(Plaines Jaunes)" },
    L10: { type: CEFType.desert.type, label: "Méandre ...\n(Désert de Nicrop)" },
    M10: { type: CEFType.foret.type, label: "Rapide ...\n(Forêt de Jajou)" },
    A11: { type: CEFType.desolation.type, label: "Ecueils ...\n(Désolation d’Hier)" },
    B11: { type: CEFType.cite.type, label: "Sémaphore ...\n(Cité de Brilz)" },
    C11: { type: CEFType.pont.type, label: "Île ...\n(Pont de Roï)" },
    D11: { type: CEFType.desolation.type, label: "Ecueils ...\n(Désolation de Partout)" },
    E11: { type: CEFType.lac.type, label: "Lac (de Glinster)" },
    F11: { type: CEFType.cite.type, label: "Sémaphore ...\n(Cité de Noape)" },
    G11: { type: CEFType.fleuve.type, label: "Fleuve de l'Oubli" },
    H11: { type: CEFType.fleuve.type, label: "Fleuve de l'Oubli" },
    I11: { type: CEFType.pont.type, label: "Île ...\n(Pont de Yalm)" },
    J11: { type: CEFType.plaines.type, label: "Banc ...\n(Plaines de Miltiar)" },
    K11: { type: CEFType.cite.type, label: "Sémaphore ...\n(Cité Tonnerre)" },
    L11: { type: CEFType.collines.type, label: "Source ...\n(Collines de Kol)" },
    M11: { type: CEFType.cite.type, label: "Sémaphore ...\n(Cité Crapaud)" },
    A12: { type: CEFType.plaines.type, label: "Banc ...\n(Plaines Sages)" },
    B12: { type: CEFType.fleuve.type, label: "Fleuve de l'Oubli" },
    C12: { type: CEFType.lac.type, label: "Lac (de Fricassa)" },
    D12: { type: CEFType.collines.type, label: "Source ...\n(Collines d’Huaï)" },
    E12: { type: CEFType.monts.type, label: "Chute ...\n(Monts Ajourés)" },
    F12: { type: CEFType.necropole.type, label: "Maelstrom ...\n(Nécropole de Throat)" },
    G12: { type: CEFType.plaines.type, label: "Banc ...\n(Plaines de Lufmil)" },
    H12: { type: CEFType.collines.type, label: "Source ...\n(Collines de Tooth)" },
    I12: { type: CEFType.gouffre.type, label: "Abîme ...\n(Gouffre Abimeux)" },
    J12: { type: CEFType.cite.type, label: "Sémaphore ...\n(Cité Folle)" },
    K12: { type: CEFType.desolation.type, label: "Ecueils ...\n(Désolation d’Amour)" },
    L12: { type: CEFType.plaines.type, label: "Banc ...\n(Plaines Venteuses)" },
    M12: { type: CEFType.collines.type, label: "Source ...\n(Collines Révulsantes)" },
    A13: { type: CEFType.fleuve.type, label: "Fleuve de l'Oubli" },
    B13: { type: CEFType.gouffre.type, label: "Abîme ...\n(Gouffre des Litiges)" },
    C13: { type: CEFType.desert.type, label: "Méandre ...\n(Désert de Neige)" },
    D13: { type: CEFType.cite.type, label: "Sémaphore ...\n(Cité Sordide)" },
    E13: { type: CEFType.plaines.type, label: "Banc ...\n(Plaines de Xnez)" },
    F13: { type: CEFType.foret.type, label: "Rapide ...\n(Forêt des Cris)" },
    G13: { type: CEFType.plaines.type, label: "Banc ...\n(Plaines Calcaires)" },
    H13: { type: CEFType.desolation.type, label: "Ecueils ...\n(Désolation de Rien)" },
    I13: { type: CEFType.monts.type, label: "Chute ...\n(Monts Bigleux)" },
    J13: { type: CEFType.gouffre.type, label: "Abîme de [Linus] ?\n(Gouffre de Gromph)" },
    K13: { type: CEFType.foret.type, label: "Rapide ...\n(Forêt de Kluth)" },
    L13: { type: CEFType.monts.type, label: "Chute ...\n(Monts Dormants)" },
    M13: { type: CEFType.plaines.type, label: "Banc ...\n(Plaines d’Anjou)" },
    A14: { type: CEFType.collines.type, label: "Source ...\n(Collines de Stolis)" },
    B14: { type: CEFType.necropole.type, label: "Maelstrom ...\n(Nécropole de Gorlo)" },
    C14: { type: CEFType.foret.type, label: "Rapide ...\n(Forêt de Bissam)" },
    D14: { type: CEFType.sanctuaire.type, label: "Chenal ...\n(Sanctuaire Plat)" },
    E14: { type: CEFType.monts.type, label: "Chute ...\n(Monts de Quath)" },
    F14: { type: CEFType.plaines.type, label: "Banc ...\n(Plaines Brisées)" },
    G14: { type: CEFType.desert.type, label: "Méandre ...\n(Désert de Sek)" },
    H14: { type: CEFType.plaines.type, label: "Banc ...\n(Plaines Blanches)" },
    I14: { type: CEFType.cite.type, label: "Sémaphore ...\n(Cité Destituée)" },
    J14: { type: CEFType.desert.type, label: "Méandre ...\n(Désert de Sank)" },
    K14: { type: CEFType.necropole.type, label: "Maelstrom ...\n(Nécropole d’Antinéar)" },
    L14: { type: CEFType.plaines.type, label: "Banc ...\n(Plaines de Jislith)" },
    M14: { type: CEFType.desolation.type, label: "Ecueils ...\n(Désolation d’Après)" },
    A15: { type: CEFType.cite.type, label: "Sémaphore ...\n(Cité de Mielh)" },
    C15: { type: CEFType.plaines.type, label: "Banc ...\n(Plaines de Toué)" },
    E15: { type: CEFType.foret.type, label: "Rapide ...\n(Forêt des Furies)" },
    G15: { type: CEFType.plaines.type, label: "Banc ...\n(Plaines des Soupirs)" },
    I15: { type: CEFType.monts.type, label: "Chute ...\n(Monts des Dragées)" },
    K15: { type: CEFType.collines.type, label: "Source ...\n(Collines Pourpres)" },
    M15: { type: CEFType.cite.type, label: "Sémaphore ...\n(Cité de Klana)" }
}